### ISSUE TITLE
trailing-slash for local URL

### ISSUE THREAD

**Issue by drzraf** [humanmade/hm-redirects#74]
WP common configuration adds a trailing-slash to URL.
`trailingslashit` is in charge for this.

When redirecting to a local URL, omitting the trailing-slash incur another redirect for the purpose of adding the slash.
The current code always drop that slash implying **two** redirections.

**Comment by svandragt** [comment]
Thanks for your contribution @drzraf it's really appreciated, I just came across s similar issue. The problem is that redirections to other sites that have the same behaviour will still result in a redirection to a trailing slash URL. So just making the exception for local URLs doesn't solve the problem.

The root cause is that the trailing slash is stripped from all TO urls (in `sanitise_and_normalise_url()`). We're looking at fixing it there.

Sorry for the delay.

**Comment by roborourke** [comment]
I think the behaviour was perhaps written with external URLs in mind, but it should probably accept what was specifically entered by the user. I think the PR looks good, will do a full review now.

**Comment by drzraf** [comment]
Dear,
Could you please reopen because #82 never fixed what was mentioned in the present issue (the double-redirect effect in case of local redirection).

thx

**Comment by svandragt** [comment]
Thanks for your feedback @drzraf it's much appreciated.
